name: example
description: example App in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.2
  webview_cookie_manager: ^1.0.8
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.3
  firebase_messaging: ^9.1.0
  flutter_local_notifications: ^5.0.0+1
  encrypt: ^5.0.0
  crypto: ^3.0.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.1.7+1


flutter:
  uses-material-design: true

  assets:
    - assets/splash/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  image: assets/splash/splash_2732x2732.png
  color: "#ffffff"
  fullscreen: true